### PR TITLE
Add DCGAN, MemN2N, NTM

### PR DESCRIPTION
**Pull request by WakumiEnritsu**
Add DCGAN, MemN2N, NTM
Tensorflow implementation are ported from carpedm20 with no change.

MemN2N: https://github.com/carpedm20/MemN2N-tensorflow
DCGAN: https://github.com/carpedm20/DCGAN-tensorflow
NTM: https://github.com/carpedm20/NTM-tensorflow
All licensed under the MIT License
For more details, please refer to the corresponding README.md.

Project has been tested. (Windows 10 16299, Visual Studio 2017 15.6.6, Python 3.6.4, TensorFlow 1.6.0)

### CODE REVIEW

**Comment by TobeyQin** [comment]
hi，thank you for your submission.
1. In the Readme file, please add an License bullet and give a clear indication of what license it has. So people can easily notice that it is under MIT license.

2. It is a little tricky of your project file(.pyproj file). In the "ProjectTypeGuids" item, you only has the GUID of AITools, but don't have the guid of tensorflow. Please check it again. The "ProjectTypeGuids" should like this: {D22814C2-A430-4A53-8052-A3A64BFB2240};{888888A0-9F3D-457C-B088-3A5042F75D52}.  The first one is the guid of tensorflow, and the second one is for ToolsForAI.

Thanks

**Comment by WakumiEnritsu** [comment]
Hi,
I've fixed the issues, please check it!

**Comment by TobeyQin** [comment]
Hi, your branch has conflict with the master branch, please resolved it first. Thanks.

**Comment by WakumiEnritsu** [comment]
Hi,
I've fixed, please check it.
________________________________
发件人: TobeyQin <notifications@github.com>
发送时间: 2018年4月23日 7:42:30
收件人: Microsoft/samples-for-ai
抄送: Tenyuuk; State change
主题: Re: [Microsoft/samples-for-ai] Add DCGAN, MemN2N, NTM (#35)


Hi, your branch has conflict with the master branch, please resolved it first. Thanks.

―

**Pull request merged**
