### PR TITLE
add rnet implementation

### PR DESCRIPTION
**Pull request by MintYiqingchen**
The training process is able to run, but the model cannnot be trained effectively.
Use this model as a demo or practice for attention mechanism and self-designed recurrence network.

### CODE REVIEW

**Comment by TobeyQin** [comment]
Hi, @MintYiqingchen, Thank you for your contribution. I am so appreciated to see these new examples. But why I didn't see the vs project files in your commitment? You need to create vs project first. Thanks.

**Comment by MintYiqingchen** [comment]
I have add it now

**Comment by MintYiqingchen** [comment]
I have added it now. : ) @TobeyQin

**Comment by TobeyQin** [comment]
Thank you very much!

**Pull request merged**
