### PR TITLE
Add WGAN/InfoGAN/DiscoGAN Keras implementation

### PR DESCRIPTION
**Pull request by nuaajeff**
Keras implementation of Paper: [Wasserstein GAN](https://arxiv.org/abs/1701.07875)
Train a simple wgan on MNIST to generate handwritten digits.
Requirements: tensorflow >= 1.4.0; Keras >= 2.1.0
Code ported from [Keras-GAN](https://github.com/eriklindernoren/Keras-GAN)

LICENSE: MIT

### CODE REVIEW

**Comment by nuaajeff** [comment]
Keras implementation of Paper: [Information Maximizing GAN](https://arxiv.org/abs/1606.03657)
Train a simple dcgan on MNIST to generate handwritten digits.
Requirements: tensorflow >= 1.4.0; Keras >= 2.1.0
Code ported from [Keras-GAN](https://github.com/eriklindernoren/Keras-GAN)

LICENSE: MIT

**Comment by nuaajeff** [comment]
Keras implementation of Paper: [DiscoGAN](https://arxiv.org/abs/1703.05192)
Requirements: tensorflow >= 1.4.0; Keras >= 2.1.0
Code ported from [Keras-GAN](https://github.com/eriklindernoren/Keras-GAN)

LICENSE: MIT

**Comment by TobeyQin** [comment]
Thank you for your submission. There is some conflict with the master branch. Pls. resolve the conflicts and commit again. Thanks!

**Comment by TobeyQin** [comment]
Thank you for your submission. There is some conflict with the master branch. Pls. resolve the conflicts and commit again. Thanks!

**Comment by nuaajeff** [comment]
All the conflicts have been resolved.

**Comment by yelenah** [comment]
Can you please advise how I can unsubscribe from receiving this emails?

Thank you,
Yelena

**Comment by mariannabudnikova** [comment]
+1

**Pull request merged**
