### PR TITLE
Fix normalize method when scale image

### PR DESCRIPTION
**Pull request by mslichao**
Previous method not change the image size, only draw a small one on the left top.

### CODE REVIEW

**Comment by shishaochen** [comment]
@mslichao Good catch on this problem! Thanks a lot!
However, the default scaling implementation of Bitmap constructor may have problem described at [C# Resizing Bitmap without changing the Pixelformat](https://stackoverflow.com/questions/28433826/c-sharp-resizing-bitmap-without-changing-the-pixelformat).
How about using function below which is the original/internal implementation of MNIST App?
```C#
public static Bitmap ResizeImage(Bitmap imgToResize, Size size)
{
    Bitmap b = new Bitmap(size.Width, size.Height);
    using (Graphics g = Graphics.FromImage(b))
    {
        g.InterpolationMode = InterpolationMode.HighQualityBicubic;
        g.DrawImage(imgToResize, 0, 0, size.Width, size.Height);
    }
    return b;
}

public static float[,] ConvertToGrayScaleArray(Bitmap image)
{
    var height = image.Size.Height;
    var width = image.Size.Width;
    var data = new float[height, width];
    for (var x = 0; x < height; x++)
    {
        for (var y = 0; y < width; y++)
        {
            // Be careful about the X/Y direction
            var color = image.GetPixel(y, x);
            // 1. Convert to gray
            // 2. Normalize to [-0.5,0.5]
            // 3. Turn to black background and white digit like MNIST dataset
            data[x, y] = (float)(0.5 - (color.R + color.G + color.B) / (3.0 * 255));
        }
    }
    return data;
}
```
Moving these 2 utilization functions to another C# file like "ImageUtils.cs" may be helpful for our customers to apply to their applications.

**Comment by mslichao** [comment]
@shishaochen Thanks for pointing out the issue of Bitmap constructor, I have fix it in the new commit.
Besides, I have reverted all my changes and only did the required change in the new commit because:
1. Keep my pull request only fix the image size issue.
2. Respect the origin author's code

**Comment by shishaochen** [comment]
I see.
Actually, I am the author of this App while the code was open sourced by others with some changes.

**Comment by linmajia** [comment]
@shishaochen and @mslichao , if you think the code needs improvement, please submit pull requests and don't worry about other things.

**Pull request merged**
